### ISSUE TITLE
py-opencl-2018.2.5 fails to compile on ppc64le on Alpine Linux

### ISSUE THREAD

**Issue by mksully22** [inducer/pyopencl#289] opened 2019-05-30 20:45 UTC
As described in Alpine issue: https://bugs.alpinelinux.org/issues/10489
Building pyopencl fails on ppc64le with errors:
```
gcc -fno-strict-aliasing -fomit-frame-pointer -DTHREAD_STACK_SIZE=0x100000 -O3 -DNDEBUG -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ipybind11/include -I/usr/include/python2.7 -I/home/mksully/.local/include/python2.7 -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c src/wrap_constants.cpp -o build/temp.linux-ppc64le-2.7/src/wrap_constants.o -fvisibility=hidden -DVERSION_INFO="2018.2.5" -std=c++14 -fvisibility=hidden
In file included from /usr/include/c++/8.3.0/ratio:38,
                 from /usr/include/c++/8.3.0/chrono:38,
                 from /usr/include/c++/8.3.0/thread:38,
                 from src/wrap_cl.hpp:76,
                 from src/wrap_constants.cpp:27:
/usr/include/c++/8.3.0/type_traits:75:39: error: '__vector(4) __bool int' is not a valid type for a template non-type parameter
   typedef integral_constant<bool, true>     true_type;
                                       ^
/usr/include/c++/8.3.0/type_traits:78:40: error: '__vector(4) __bool int' is not a valid type for a template non-type parameter
   typedef integral_constant<bool, false>    false_type;
                                        ^
/usr/include/c++/8.3.0/type_traits:81:56: error: '__vector(4) __bool int' is not a valid type for a template non-type parameter
     using __bool_constant = integral_constant<bool, __v>;
                                                        ^
/usr/include/c++/8.3.0/type_traits:100:5: error: expected class-name before '{' token
     { };
     ^
```

Removing the code introduced into setup.py by https://github.com/inducer/pyopencl/commit/6fe7f4a6fe56819c66155c1764ed6367d5a286e7 and later moved to aksetup_helper.py by https://github.com/inducer/pyopencl/commit/d8a1a7fab22e798611edb881d3edad38712fae68 and https://github.com/inducer/pyopencl/commit/e9b66cd3d669973b3fb0273a8bd23c729553eeea
allows the code to compile successfully.

Is this a known issue or are there some other steps or options I can use to build successfully?

**Comment by inducer** [comment] 2019-05-30 20:59
Dupe of #280 (IMO). Try git master.

**Closed as completed by inducer** 2019-05-30 20:59 UTC
