### ISSUE TITLE
Installation failure occurs consistently with latest/older pyopencl versions

### ISSUE THREAD

**Issue by ccarpita** [inducer/pyopencl#324] opened 2020-01-15 23:33 UTC
## Repro Steps

```
python --version
# > Python 3.6.3

rm -rf .venv
python -m venv .venv
source .venv/bin/activate
pip install -U pip

pip install -v --no-cache-dir pyopencl
```

## Error Message
```
    Traceback (most recent call last):
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/tools/cythonize.py", line 238, in <module>
        main()
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/tools/cythonize.py", line 66, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    /var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File ".venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File .venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File ".venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File ".venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/setup.py", line 488, in <module>
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/setup.py", line 469, in setup_package
      File "/var/folders/8j/jgzqhljj5vl4p2831sh_gxvw0000gp/T/easy_install-9h2nycjh/numpy-1.18.1/setup.py", line 275, in generate_cython
        cmdclass={'build_ext': PybindBuildExtCommand},
    RuntimeError: Running cythonize failed!
```

## Mitigations

1. Instruct users to install the latest version of numpy before this package (not ideal)
```
pip install numpy
```

2. Create `pyproject.toml` for this repo and specify build dependency on numpy

## Root Causes

It seems that easy_install is used on this package's dependencies for numpy, and so its [pyproject.toml](https://github.com/numpy/numpy/blob/master/pyproject.toml) file is not respected. This file specifies that Cython is required for setup, and would be handled if pip were used on transitive dependencies.

**Comment by inducer** [comment] 2020-01-16 04:00
Thanks for the report and the thorough investigation!

> specify build dependency on Cython

Does declaring a build dep on `numpy` in `pypropject.toml` suffice?

**Comment by ccarpita** [comment] 2020-01-16 14:58
@inducer I believe that your proposed solution would work, since `pip` would then be aware of the dependency and perform the `numpy` installation (if needed) before attempting to execute the `setup.py` script of `pyopencl`. This might be the most technically correct thing too, since `numpy` is effectively needed for the build process.

**Comment by inducer** [comment] 2020-01-28 01:30
FWIW, I can't reproduce your issue.

```
pip install -v --no-cache-dir pyopencl
```
pulls in binary wheels and succeeds

Also
```sh
pip install pybind11  # inelegant! perhaps fixed by #326
pip install -v --no-cache-dir --no-binary :all: pyopencl
```
builds everything from source and also seems to succeed.

Meanwhile, #326 makes the change you request, which I'm willing to consider since it sounds like the right thing, and it might fix the pybind11 issue. Could you please verify that
```
pip install -v --no-cache-dir --no-binary :all: git+https://github.com/inducer/pyopencl.git@pyproject-toml
```
addresses your issue? It does succeed for me (without installing `pybind11`).

**Comment by ccarpita** [comment] 2020-01-28 16:28
The install of the branch fails with the error:
```
      setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      /Users/ccarpita/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      error: invalid command 'bdist_wheel'
      Preparing wheel metadata: finished with status 'error'
```

However, it appears that it did generate sources using Cython correctly, so that's an improvement!

Regarding reproduction, I would ensure the following:

1. Use a clean virtualenv
2. `pip version` provides `pip 20.0.2`
3. `python --version` provides `Python 3.6.3`

I'm guessing that I might not be getting the wheel distribution because of my OS/arch, which is:
OSX 10.15, MacBookPro16,1, 8-Core Intel Core i9

**Comment by ccarpita** [comment] 2020-01-28 16:29
Also note that `pip install -v --no-cache-dir git+https://github.com/inducer/pyopencl.git@pyproject-toml` succeeds for me, as the binaries for numpy will be used and I won't run into the above error

**Comment by inducer** [comment] 2020-01-28 23:12
```
error: invalid command 'bdist_wheel'
```
suggests that the `wheel` package is missing, however `pyopencl`'s `pyproject.toml` specifically asks for that to be there. Weird. I'm guessing this is a separate issue. At any rate, thanks for reporting back. It seems that #326 provides an improvement, so I'll go ahead and merge it.

**Comment by inducer** [comment] 2020-01-28 23:13
Do you think we can close this? Or do you think there's anything further that should be done?

**Comment by ccarpita** [comment] 2020-01-29 20:29
Yes, I think given the successful installation test, we can close the issue. Thanks!

**Closed as completed** 2020-01-29 20:36 UTC
